# Psalm 23 ESV Mad Libs Games
# Python 3.0 

print("The Lord is my shepherd; I shall not want")
print("He makes me lie down in green pastures.")
print("He leads me beside still waters.")
print("He restores my soul")
print("He leads me in paths of righteoughness")
print("for his name's sake.")
print("")
print("Even though I walk through the valley of death,")
print("I will fear no evil")
print("for you are with me;")
print("your rod and your staff,")
print("they comfort me.")
print("")
print("You prepare a table before me")
print("in the presence of my enemies")
print("you anoint my head with oil")
print("my cup overflows")
print("Surely goodness and mercy shall follow me")
print("all the days of the my life,")
print("and I shall dwell in the house of the Lord forever")
print("")

lord = input("Enter lord ")
color = input("Enter color ")
water = input("Enter water ")
soul = input("Enter soul ")
paths = input("Enter paths ")
sake = input("Enter sake ")

print("The " + lord + " is my shepherd; I shall not want")
print("He makes me lie down in " + color + " pastures.")
print("He leads me beside still " + water + ".")
print("He restores my " + soul + "")
print("He leads me in " + paths + " of righteoughness")
print("for his name's " + sake + ".")

death = input("Enter death ")
evil = input("Enter evil ")
me = input("Enter me ")
rod = input("Enter rod ")
staff = input("Enter staff ")
comfort = input("Enter comfort ")

print("Even though I walk through the valley of " + lord + ",")
print("I will fear no " + evil)
print("for you are with " + me)
print("your " + rod + " and your " + staff + ",")
print("they comfort " + comfort + ".")
print("")

table = input("Enter table ")
enemies = input("Enter enemies ")
head = input("Enter head ")
cup = input("Enter cup ")
oil = input("Enter oil ")
follow = input("Enter follow ")
life = input("Enter life ")
forever = input("Enter forever ")

print("You prepare a " + table + " before me")
print("in the presence of my " + enemies + "")
print("you anoint my " + head + " with " + oil)
print("my " + cup + " overflows")
print("Surely goodness and mercy shall " + follow + " me")
print("all the days of the my " + life + ",")
print("and I shall dwell in the house of the Lord " + forever + "")